# Generated by Django 5.2.5 on 2025-08-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_child_can_pickup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='can_pickup',
        ),
        migrations.AddField(
            model_name='parent',
            name='can_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
