# Generated by Django 5.2.5 on 2025-08-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_child_can_pickup_parent_can_pickup'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='year',
            field=models.IntegerField(choices=[(2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], default=2025, verbose_name='Año'),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('paid', 'month', 'year')},
        ),
    ]
