# Generated by Django 5.2.5 on 2025-08-31 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bill_unique_together_alter_bill_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='nip',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='nip',
        ),
    ]
