# Generated by Django 5.2.5 on 2025-08-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_parent_nip_remove_professor_nip'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='nip',
            field=models.CharField(max_length=50, null=True, verbose_name='NIP'),
        ),
        migrations.AddField(
            model_name='professor',
            name='nip',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='NIP'),
        ),
    ]
