# Generated by Django 5.2.5 on 2025-08-31 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_parent_nip_professor_nip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='nip',
        ),
        migrations.AlterField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL),
        ),
    ]
