# Generated by Django 5.2.5 on 2025-08-31 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_professor_nip_alter_professor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='nip',
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
