# Generated by Django 5.2.5 on 2025-08-31 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_parent_nip_alter_parent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='nip',
            field=models.CharField(max_length=50, null=True, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
