# Generated by Django 5.2.5 on 2025-09-02 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_parent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='nip',
        ),
    ]
